# Shooter Arena v1.0.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013


defaultWorldName: world

shooterPower: 4
shooterCost: 10

reviveExp: true
reviveExpSeconds: 15
reviveExpAmount: 100

catapultOnRespawn: true
catapultPower: 5

kits:
  giveExp: 1500
  items: '267^16-2,(shooter),282:10'
  armors: '0,299$667F33,300$667F33,0'

chatMode: team
