# Shooter Arena v1.0.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013
#
# defaultWorldName: ShooterArenaで遊ぶワールドの、ワールド名を指定します。
# defaultWorldName: Shooterのパワーレベルを指定します。
# shooterCost: Shooterを一回打つのに必要なコストを設定します。
# reviveExp: 燃料切れになったときに、一定時間経過後に燃料が再提供されるかどうかを設定します。
# reviveExpSeconds: reviveExp が true の場合、燃料切れになってから何秒で再燃料が提供されるかを設定します。
# reviveExpAmount: reviveExp が true の場合、再提供される量を設定します。
# catapultOnRespawn: リスポーン時に射出されるかどうかを設定します。
# catapultPower: catapultOnRespawn が true の場合、射出する速度を設定します。
# kits: ゲーム開始時の配布設定
# kits.giveExp: ゲーム開始時に配布するexpを設定します。
# kits.items: ゲーム開始時に配布するアイテムを設定します。
# kits.armors: ゲーム開始時に配布する防具を設定します。
# chatMode: チャットモードを設定します。（global: 通常のチャット、arena: アリーナ内限定、team: チーム内限定）

defaultWorldName: world

shooterPower: 5
shooterCost: 10

reviveExp: true
reviveExpSeconds: 15
reviveExpAmount: 100

catapultOnRespawn: true
catapultPower: 5

kits:
  giveExp: 1500
  items: ''
  armors: ''

chatMode: team
